# This file is automatically generated. Do not edit.

if Object.const_defined?('TestFlight') and !UIDevice.currentDevice.model.include?('Simulator')
  NSNotificationCenter.defaultCenter.addObserverForName(UIApplicationDidBecomeActiveNotification, object:nil, queue:nil, usingBlock:lambda do |notification|
  
  TestFlight.takeOff('9f13c5e133f3ebf02f7781e9819be27f_MTEwNzE2MjAxMi0wNy0xNiAxMToxNzozNi43MzY0NzU')
  end)
end
